### ISSUE TITLE
Model baseclass follow-up todo's

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/ewatercycle#359]
- [x] Update tests for abstractmodel to test the new API (once crystallized)
- [x] Update documentation
- [x] Remove `new_model_api.py` from repo.
- [x] Nice to have: Extend containerimage class to check version
- [ ] Nice to have: Extend containerimage class to automatically pull docker image and convert to singularity

and

- [x] iron out post_init / _parse_config (https://github.com/eWaterCycle/ewatercycle/pull/354#discussion_r1275998129)
- [x] reset `get_parameters` back to `parameters` property
- [ ] Version check: we could probaly reimplement an alternative version check validator on the eWaterCycle model

**Comment by sverhoeven** [comment]
See https://pymt.readthedocs.io/en/latest/usage.html#model-setup for why we want bmi.parameters

**Comment by Peter9192** [comment]
Remaining documentation issues will be addressed after the v2 release.
